# This is a config for E2B sandbox template.
# You can use template ID (qraxoojmljabjrgew06f) or template name (vibe-nextjs-amantest4) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-amantest4") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-amantest4") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-amantest4')

team_id = "81405a6f-2b9c-45f9-b0d1-c697bcd3d57f"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-amantest4"
template_id = "qraxoojmljabjrgew06f"
