# This is a config for E2B sandbox template.
# You can use template ID (v5rm3lsiq1ais32s3zwp) or template name (vibe-nextjs-tests-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-tests-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-tests-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-tests-2')

team_id = "81405a6f-2b9c-45f9-b0d1-c697bcd3d57f"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-tests-2"
template_id = "v5rm3lsiq1ais32s3zwp"
